#!/usr/bin/python

import signal
import SimpleHTTPServer
import SocketServer
import sys

PORT = 8888

# http://stackoverflow.com/a/25375077
class SSPHTTPHandler(SimpleHTTPServer.SimpleHTTPRequestHandler):

    def log_message(self, format, *args):
		"""
			Format the log messages generated by requests to the server.
		"""
		print("[%s]: %s ==> %s" % (self.log_date_time_string(), self.client_address[0], format%args))
		#print("[%s]: %s ==> %s" % (self.log_date_time_string(), self.client_address[0], args[1]))

class sspserver():
	
	def __init__(self):
		
		try:
			Handler = SSPHTTPHandler
			httpd = SocketServer.TCPServer(("", PORT), Handler)
			print "Serving on port", PORT
			httpd.serve_forever()
		except KeyboardInterrupt:
			sys.exit(0)
	
if __name__ == "__main__":
	s = sspserver()